// import { Inter } from 'next/font/google';
import { poppins } from './fonts';

import '../custom-styles/custom-styles.css';
import './globals.css';
import Header from '@/components/layout/Header';
import { Toaster } from 'sonner';

// const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: {
    default: 'Portfolio Website',
    template: '%s | Portfolio Website'
  },
  description: 'Generated by John Paul'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable} suppressHydrationWarning>
      <body className={`dark ${poppins.className}`}>
        <Header />
        {children}
        <Toaster position="bottom-center" />
      </body>
    </html>
  );
}
